[package]
name = "basic-server"
version = "0.1.0"
authors = ["WolvenSpirit"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "basic-server"
path = "main.rs"
